name: test_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/logger
  logger: ^2.3.0
  
  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.2.5

  # https://pub.dev/packages/web3modal_flutter
  web3modal_flutter: 3.2.0

dev_dependencies:
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^4.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true